version: "3"

services:
  app_uau:
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.backend=app_uau
      - traefik.frontend.rule=Host:app.tagbss.com
      
  reverse-proxy:
      image: traefik
      command: --api --docker.exposedbydefault=false
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock